/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;
import javax.swing.UIManager;

/**
 *
 * @author ACER
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
        
        // Add document listener to suhuTextField
        suhuTextField.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateHasil();
            }
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateHasil();
            }
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateHasil();
            }
        });
        
        // Add action listener to combo box
        suhuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHasil();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        groupSuhu = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        besarSuhuLabel = new javax.swing.JLabel();
        suhuTextField = new javax.swing.JTextField();
        celciusRadioButton = new javax.swing.JRadioButton();
        reamurRadioButton = new javax.swing.JRadioButton();
        fahrenheitRadioButton = new javax.swing.JRadioButton();
        kelvinRadioButton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        suhuComboBox = new javax.swing.JComboBox<>();
        hasilLabel = new javax.swing.JLabel();
        hasilTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        convertButton = new javax.swing.JButton();
        judulLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suhu Yang Dikonversi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei Light", 1, 14))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        besarSuhuLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        besarSuhuLabel.setText("Besarnya Suhu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(14, 5, 0, 5);
        jPanel1.add(besarSuhuLabel, gridBagConstraints);

        suhuTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuTextFieldActionPerformed(evt);
            }
        });
        suhuTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                suhuTextFieldKeyTyped(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel1.add(suhuTextField, gridBagConstraints);

        groupSuhu.add(celciusRadioButton);
        celciusRadioButton.setText("Celcius");
        celciusRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                celciusRadioButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 7);
        jPanel1.add(celciusRadioButton, gridBagConstraints);

        groupSuhu.add(reamurRadioButton);
        reamurRadioButton.setText("Reamur");
        reamurRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reamurRadioButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 8);
        jPanel1.add(reamurRadioButton, gridBagConstraints);

        groupSuhu.add(fahrenheitRadioButton);
        fahrenheitRadioButton.setText("Fahrenheit");
        fahrenheitRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fahrenheitRadioButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 8);
        jPanel1.add(fahrenheitRadioButton, gridBagConstraints);

        groupSuhu.add(kelvinRadioButton);
        kelvinRadioButton.setText("Kelvin");
        kelvinRadioButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                kelvinRadioButtonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(16, 0, 16, 1);
        jPanel1.add(kelvinRadioButton, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suhu Hasil Konversi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft YaHei Light", 1, 14))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        suhuComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Reamur", "Fahrenheit", "Kelvin" }));
        suhuComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suhuComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 4);
        jPanel2.add(suhuComboBox, gridBagConstraints);

        hasilLabel.setText("Hasil");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(8, 3, 7, 0);
        jPanel2.add(hasilLabel, gridBagConstraints);

        hasilTextField.setFocusable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(8, 6, 7, 4);
        jPanel2.add(hasilTextField, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel3.add(closeButton, gridBagConstraints);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 22, 0);
        jPanel3.add(convertButton, gridBagConstraints);

        judulLabel.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        judulLabel.setForeground(new java.awt.Color(102, 102, 102));
        judulLabel.setText("Aplikasi Konversi Suhu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(judulLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(judulLabel)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        //converter suhu
        try {
        double suhu = Double.parseDouble(suhuTextField.getText());
        double hasil = 0;
        String satuanAwal = "";
        
        if (celciusRadioButton.isSelected()) {
            satuanAwal = "Celcius";
        } else if (reamurRadioButton.isSelected()) {
            satuanAwal = "Reamur";
        } else if (fahrenheitRadioButton.isSelected()) {
            satuanAwal = "Fahrenheit";
        } else if (kelvinRadioButton.isSelected()) {
            satuanAwal = "Kelvin";
        } else {
            throw new Exception("Pilih satuan suhu awal.");
        }
        
        String satuanTujuan = (String) suhuComboBox.getSelectedItem();
        
        switch (satuanAwal) {
            case "Celcius":
                if (satuanTujuan.equals("Reamur")) {
                    hasil = suhu * 4 / 5;
                } else if (satuanTujuan.equals("Fahrenheit")) {
                    hasil = suhu * 9 / 5 + 32;
                } else if (satuanTujuan.equals("Kelvin")) {
                    hasil = suhu + 273.15;
                } else {
                    hasil = suhu;
                }
                break;
            case "Reamur":
                if (satuanTujuan.equals("Celcius")) {
                    hasil = suhu * 5 / 4;
                } else if (satuanTujuan.equals("Fahrenheit")) {
                    hasil = suhu * 9 / 4 + 32;
                } else if (satuanTujuan.equals("Kelvin")) {
                    hasil = suhu * 5 / 4 + 273.15;
                } else {
                    hasil = suhu;
                }
                break;
            case "Fahrenheit":
                if (satuanTujuan.equals("Celcius")) {
                    hasil = (suhu - 32) * 5 / 9;
                } else if (satuanTujuan.equals("Reamur")) {
                    hasil = (suhu - 32) * 4 / 9;
                } else if (satuanTujuan.equals("Kelvin")) {
                    hasil = (suhu - 32) * 5 / 9 + 273.15;
                } else {
                    hasil = suhu;
                }
                break;
            case "Kelvin":
                if (satuanTujuan.equals("Celcius")) {
                    hasil = suhu - 273.15;
                } else if (satuanTujuan.equals("Reamur")) {
                    hasil = (suhu - 273.15) * 4 / 5;
                } else if (satuanTujuan.equals("Fahrenheit")) {
                    hasil = (suhu - 273.15) * 9 / 5 + 32;
                } else {
                    hasil = suhu;
                }
                break;
        }
        
        //tampilan hasil
        hasilTextField.setText(String.valueOf(hasil));
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Input tidak valid. Masukkan angka yang benar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    } 
        //error saat mengklik button convert jika yang diisi bukan angka
        catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_convertButtonActionPerformed

    private void suhuComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuComboBoxActionPerformed

    private void suhuTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suhuTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suhuTextFieldActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        //konfirmasi keluar dari aplikasi jika button close di klik
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Apakah anda yakin ingin keluar?",
            "Konfirmasi",
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeButtonActionPerformed

    private void suhuTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suhuTextFieldKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0' && c <= '9') || c == '.' || c == '-' || c == KeyEvent.VK_BACK_SPACE || c == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
        
    }//GEN-LAST:event_suhuTextFieldKeyTyped

    private void reamurRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reamurRadioButtonItemStateChanged
        updateHasil();
    }//GEN-LAST:event_reamurRadioButtonItemStateChanged

    private void celciusRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_celciusRadioButtonItemStateChanged
        updateHasil();
    }//GEN-LAST:event_celciusRadioButtonItemStateChanged

    private void fahrenheitRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fahrenheitRadioButtonItemStateChanged
        updateHasil();
    }//GEN-LAST:event_fahrenheitRadioButtonItemStateChanged

    private void kelvinRadioButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_kelvinRadioButtonItemStateChanged
        updateHasil();
    }//GEN-LAST:event_kelvinRadioButtonItemStateChanged

    private void updateHasil() {
        try {
            if (suhuTextField.getText().isEmpty()) {
                hasilTextField.setText("");
                return;
            }
            
            double suhu = Double.parseDouble(suhuTextField.getText());
            double hasil = 0;
            String satuanAwal = "";
            
            if (celciusRadioButton.isSelected()) {
                satuanAwal = "Celcius";
            } else if (reamurRadioButton.isSelected()) {
                satuanAwal = "Reamur";
            } else if (fahrenheitRadioButton.isSelected()) {
                satuanAwal = "Fahrenheit";
            } else if (kelvinRadioButton.isSelected()) {
                satuanAwal = "Kelvin";
            } else {
                hasilTextField.setText("");
                return;
            }
            
            String satuanTujuan = (String) suhuComboBox.getSelectedItem();
            
            switch (satuanAwal) {
                case "Celcius":
                    if (satuanTujuan.equals("Reamur")) {
                        hasil = suhu * 4 / 5;
                    } else if (satuanTujuan.equals("Fahrenheit")) {
                        hasil = suhu * 9 / 5 + 32;
                    } else if (satuanTujuan.equals("Kelvin")) {
                        hasil = suhu + 273.15;
                    } else {
                        hasil = suhu;
                    }
                    break;
                case "Reamur":
                    if (satuanTujuan.equals("Celcius")) {
                        hasil = suhu * 5 / 4;
                    } else if (satuanTujuan.equals("Fahrenheit")) {
                        hasil = suhu * 9 / 4 + 32;
                    } else if (satuanTujuan.equals("Kelvin")) {
                        hasil = suhu * 5 / 4 + 273.15;
                    } else {
                        hasil = suhu;
                    }
                    break;
                case "Fahrenheit":
                    if (satuanTujuan.equals("Celcius")) {
                        hasil = (suhu - 32) * 5 / 9;
                    } else if (satuanTujuan.equals("Reamur")) {
                        hasil = (suhu - 32) * 4 / 9;
                    } else if (satuanTujuan.equals("Kelvin")) {
                        hasil = (suhu - 32) * 5 / 9 + 273.15;
                    } else {
                        hasil = suhu;
                    }
                    break;
                case "Kelvin":
                    if (satuanTujuan.equals("Celcius")) {
                        hasil = suhu - 273.15;
                    } else if (satuanTujuan.equals("Reamur")) {
                        hasil = (suhu - 273.15) * 4 / 5;
                    } else if (satuanTujuan.equals("Fahrenheit")) {
                        hasil = (suhu - 273.15) * 9 / 5 + 32;
                    } else {
                        hasil = suhu;
                    }
                    break;
            }
            
            // Format hasil to 2 decimal places
            String formattedHasil = String.format("%.2f", hasil);
            hasilTextField.setText(formattedHasil);
        } catch (NumberFormatException e) {
            hasilTextField.setText("");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel besarSuhuLabel;
    private javax.swing.JRadioButton celciusRadioButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton convertButton;
    private javax.swing.JRadioButton fahrenheitRadioButton;
    private javax.swing.ButtonGroup groupSuhu;
    private javax.swing.JLabel hasilLabel;
    private javax.swing.JTextField hasilTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JRadioButton kelvinRadioButton;
    private javax.swing.JRadioButton reamurRadioButton;
    private javax.swing.JComboBox<String> suhuComboBox;
    private javax.swing.JTextField suhuTextField;
    // End of variables declaration//GEN-END:variables
}
